### PR TITLE
Fixes Connect to running issue and minor improvements

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by oscarfh** [comment]
I've accepted the merge, but when I run the build for the first time, I get the connection error. Running it again works.

**Comment by aslakknutsen** [comment]
Yeah, see comment here;
https://github.com/arquillian/arquillian-cube/issues/274#issuecomment-179302978
 :)

**Comment by oscarfh** [comment]
Cool! Sorry, I didn't see that one :)
I will try that with another image and let you know how it goes :)

**Comment by aslakknutsen** [comment]
try jboss/wildfly:8 or jboss/wildfly:9

Those should atleast work. Need to figure out what to do about centos:7

**Comment by oscarfh** [comment]
Same problem with FROM jboss/wildfly:8.2.1.Final

**Comment by aslakknutsen** [comment]
yeah, see https://github.com/jboss-dockerfiles/base/issues/5

**Pull request merged**
